# Generated by Django 5.2.6 on 2025-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('lecture', 'Guest Lecture'), ('competition', 'Competition')], max_length=20)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('registration_link', models.URLField(blank=True)),
                ('is_past_event', models.BooleanField(default=False)),
                ('report_pdf', models.FileField(blank=True, upload_to='event_reports/')),
                ('thumbnail', models.ImageField(upload_to='event_thumbnails/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('faculty', 'Faculty'), ('convenor', 'Convenor'), ('committee', 'Committee'), ('member', 'Member'), ('tech', 'Tech Team'), ('graphics', 'Graphics Team'), ('pr', 'PR Team'), ('manage', 'Management Team')], max_length=20, null='False')),
                ('designation', models.CharField(max_length=100, null='False')),
                ('year_range', models.CharField(max_length=20, null='False')),
                ('image', models.ImageField(upload_to='team/')),
                ('linkedin', models.URLField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('additional_info', models.TextField(blank=True)),
            ],
        ),
    ]
