# Generated by Django 5.2.6 on 2025-09-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(max_length=100, null='True'),
        ),
    ]
