# Generated by Django 5.2.6 on 2025-09-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember_instagram_alter_teammember_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null='False'),
        ),
    ]
